name: doctor_finder_flutter
description: A Flutter app to find doctors nearby with appointments and reviews.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5

  # State Management
  provider: ^6.1.5

  # Google Maps
  google_maps_flutter: ^2.10.1
  geolocator: ^10.1.1
  permission_handler: ^11.3.1

  # UI Components
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1

  # Navigation
  go_router: ^12.1.3

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/logo.png
    - assets/images/doctor-placeholder.png